import React from "react";
import { jsPDF } from "jspdf";
import "jspdf-autotable";

function ExportReport({ inventory = [] }) {
  const today = new Date().toLocaleDateString();

  const getDisplayRiskName = (riskLevel) => {
    if (riskLevel === "High") return "Critical";
    if (riskLevel === "Medium") return "At Risk";
    return "Safe";
  };

  const handleExportPDF = () => {
    try {
      console.log("Export PDF clicked");

      const doc = new jsPDF();
      const reportId = `INV-${Date.now()}`;
      const formattedDate = new Date().toLocaleDateString();

      doc.setFontSize(20);
      doc.text("StockGuard Inc.", 14, 18);

      doc.setFontSize(14);
      doc.text("Official Inventory Report", 14, 28);

      doc.setFontSize(11);
      doc.text(`Report ID: ${reportId}`, 14, 38);
      doc.text(`Date: ${formattedDate}`, 14, 45);
      doc.text(`Total Items: ${inventory.length}`, 14, 52);
      doc.text("Status: Active", 14, 59);

      const highRiskCount = inventory.filter((item) => item.riskLevel === "High").length;
      const mediumRiskCount = inventory.filter((item) => item.riskLevel === "Medium").length;
      const lowRiskCount = inventory.filter((item) => item.riskLevel === "Low").length;

      doc.autoTable({
        startY: 68,
        head: [["Summary", "Count"]],
        body: [
          ["Critical Items", highRiskCount],
          ["At Risk Items", mediumRiskCount],
          ["Safe Items", lowRiskCount]
        ],
        theme: "grid",
        headStyles: { fillColor: [37, 99, 235] },
        styles: { fontSize: 10 }
      });

      const rows = inventory.map((item) => [
        item.itemName,
        item.currentStock,
        item.reorderThreshold,
        getDisplayRiskName(item.riskLevel)
      ]);

      doc.autoTable({
        startY: doc.lastAutoTable.finalY + 10,
        head: [["Item Name", "Current Stock", "Threshold", "Risk Level"]],
        body: rows,
        theme: "grid",
        headStyles: { fillColor: [29, 78, 216] },
        styles: { fontSize: 10 }
      });

      doc.setFontSize(10);
      doc.text("Generated by StockGuard System", 14, doc.lastAutoTable.finalY + 18);
      doc.text("Confidential Business Report", 14, doc.lastAutoTable.finalY + 24);

      doc.save(`inventory-report-${Date.now()}.pdf`);
    } catch (error) {
      console.error("PDF export failed:", error);
      alert("PDF export failed. Check browser console.");
    }
  };

  return (
    <div className="report-container">
      <div className="report-header">
        <div>
          <h1>📦 StockGuard Inc.</h1>
          <p className="report-subtitle">Official Inventory Report</p>
          <p className="report-id">Report ID: INV-{Date.now()}</p>
        </div>

        <div className="report-meta">
          <p><strong>Date:</strong> {today}</p>
          <p><strong>Total Items:</strong> {inventory.length}</p>
          <p><strong>Status:</strong> Active</p>
        </div>
      </div>

      <div className="report-actions">
        <button type="button" onClick={handleExportPDF}>
          Export PDF
        </button>
      </div>

      <h3>Inventory Overview</h3>

      <div className="report-summary">
        <div>Critical: {inventory.filter((i) => i.riskLevel === "High").length}</div>
        <div>At Risk: {inventory.filter((i) => i.riskLevel === "Medium").length}</div>
        <div>Safe: {inventory.filter((i) => i.riskLevel === "Low").length}</div>
      </div>

      <table>
        <thead>
          <tr>
            <th>Item Name</th>
            <th>Current Stock</th>
            <th>Threshold</th>
            <th>Risk Level</th>
          </tr>
        </thead>

        <tbody>
          {inventory.map((item) => (
            <tr key={item._id}>
              <td>{item.itemName}</td>
              <td>{item.currentStock}</td>
              <td>{item.reorderThreshold}</td>
              <td className={`risk-${item.riskLevel.toLowerCase()}`}>
                {getDisplayRiskName(item.riskLevel)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="report-footer">
        <p>Generated by StockGuard System</p>
        <p>Confidential Business Report</p>
      </div>
    </div>
  );
}

export default ExportReport;